@startuml
title Container diagram for PropDevelopment

skinparam componentStyle rectangle
skinparam linetype ortho

actor "Клиент" as client
actor "Собственник" as owner
actor "Менеджер" as manager
actor "Бухгалтер" as accountant
actor "Бизнес-аналитик" as business_analyst
actor "Аналитик BI" as bi_analyst

cloud "Поставщик ресурсов ЖКХ" as utility_provider
cloud "Платёжная система" as payment_system
cloud "Государственные\nрегистрационные органы" as registry_org

package "PropDevelopment" {
    rectangle "Витрина продаж\n[JavaScript, React]\nВитрина для подбора и\nбронирования объектов недвижимости" as showcase_sales
    
    rectangle "client-crm-app\n[SpringBoot, ElasticSearch,\nDynamics CRM]\nСистема управления\nклиентскими данными" as client_crm_app
    database "crm-db\n[MSSQL]\nБаза данных системы CRM" as crm_db
    
    rectangle "client-mart-app\n[Kotlin, SpringBoot]\nПриложение для:\n- предоставления информации\n  об объектах недвижимости,\n- проведения онлайн-сделок" as client_mart_app
    database "client-mart-db\n[PostgreSQL]\nБаза данных для хранения\nинформации об объектах\nнедвижимости и сделкам" as client_mart_db
    
    rectangle "client-mart-estate-app\n[Kotlin, SpringBoot]\nПриложение для управления\nинформацией об объектах\nнедвижимости" as client_mart_estate_app
    database "client-mart-estate-db\n[PostgreSQL]\nБаза данных объектов\nнедвижимости" as client_mart_estate_db
    
    rectangle "client-tour-app\n[Kotlin, SpringBoot]\nПриложение для проведения\n3D-тура по объекту\nнедвижимости (онлайн-тур)" as client_tour_app
    database "client-tour-db\n[PostgreSQL]\nБаза данных проведения\nонлайн-тура" as client_tour_db
    
    rectangle "auth-service-1\n[Keycloak]\nСервис аутентификации\nпокупателей" as auth_service_buyer
    database "auth-db-1\n[PostgreSQL]\nБаза данных сервиса\nаутентификации покупателей" as auth_db_buyer
    
    rectangle "CRM\n[Kotlin, Spring Boot]\nСистема управления\nданными собственников" as crm
    database "crm-tenant-db\n[PostgreSQL]\nБаза данных CRM\nпо собственникам" as crm_tenant_db
    
    rectangle "tenant-core-app\n[Kotlin, SpringBoot]\nПриложение для предоставления\nуслуг собственникам" as tenant_core_app
    database "tenant-core-db\n[PostgreSQL]\nБаза данных услуг ЖКХ\nпо собственникам" as tenant_core_db
    
    rectangle "Витрина сервисов\nдля собственников\n[Mobile app iOS, Android]\nМобильные приложения\nдля собственников" as showcase_tenant
    
    rectangle "Хранилище данных\n[Greenplum]\nЕдиное хранилище данных\nдля всех систем компании" as data_warehouse
    database "DWH Хранилище\n[S3]\nФизическое хранилище\nданных DWH" as dwh_storage
    
    rectangle "Active Directory\n[MS Active Directory]\nСлужба каталогов,\nобслуживает финансовые\nсервисы" as active_directory_finance
    rectangle "Active Directory\n[MS Active Directory]\nСлужба каталогов,\nобслуживает прикладные\nбизнес-системы" as active_directory_business
    
    rectangle "accountant-service-1\n[Keycloak]\nСистема бухгалтерского\nучёта" as accountant_service
}

' Связи с людьми
client --> showcase_sales : Использует\nHTTPS
owner --> showcase_tenant : Использует\nHTTPS
manager --> client_crm_app : Работает с\nREST
manager --> crm : Работает с\nREST
accountant --> accountant_service : Использует\nREST
business_analyst --> data_warehouse : Анализирует данные\nREST
bi_analyst --> data_warehouse : Анализирует данные\nREST

' Связи между контейнерами - Витрина продаж
showcase_sales --> auth_service_buyer : Регистрация\nАутентификация\n[REST]
showcase_sales --> client_crm_app : Регистрация клиента\nКарточка клиента\nПрофиль клиента\n[REST]
showcase_sales --> client_mart_estate_app : Получить данные по\nобъектам недвижимости\n[REST]
showcase_sales --> client_tour_app : Проведение тура\n[REST]

' Связи аутентификации
auth_service_buyer --> auth_db_buyer : Читает/Записывает\n[JDBC]
showcase_tenant --> auth_service_buyer : Регистрация\nАутентификация\n[REST]
showcase_tenant --> crm : Получение данных\n[REST]
showcase_tenant --> tenant_core_app : Использование услуг\n[REST, WS]

' Связи CRM
client_crm_app --> crm_db : Читает/Записывает\n[JDBC]
client_crm_app --> client_mart_app : Публикация каталога\nобъектов\n[Kafka]
client_crm_app --> client_tour_app : Управление турами\n[REST]
client_crm_app --> active_directory_finance : Аутентификация\nменеджеров\n[LDAP]

' Связи CRM для собственников
crm --> crm_tenant_db : Читает/Записывает\n[JDBC]
crm --> active_directory_finance : Аутентификация\nменеджеров\n[LDAP]

' Связи client-mart
client_mart_app --> client_mart_db : Читает/Записывает\n[JDBC]
client_mart_estate_app --> client_mart_estate_db : Читает/Записывает\n[JDBC]
client_tour_app --> client_tour_db : Читает/Записывает\n[JDBC]

' Связи tenant-core
tenant_core_app --> tenant_core_db : Читает/Записывает\n[JDBC]
tenant_core_app --> crm : Получение клиентских\nданных\n[REST]
tenant_core_app --> payment_system : Обработка платежей\n[REST]
tenant_core_app --> utility_provider : Получение данных ЖКХ\n[REST, WS]

' Связи с хранилищем данных
crm_db --> data_warehouse : Передача сырых данных\n[CDC]
client_mart_db --> data_warehouse : Передача сырых данных\n[CDC]
client_mart_estate_db --> data_warehouse : Передача сырых данных\n[CDC]
crm_tenant_db --> data_warehouse : Передача сырых данных\n[CDC]
tenant_core_db --> data_warehouse : Передача сырых данных\n[CDC]
data_warehouse --> dwh_storage : Хранит данные\n[JDBC]
data_warehouse --> active_directory_finance : Аутентификация\nбизнес-аналитика\n[LDAP]

' Связи с внешними системами
client_mart_app --> registry_org : СМЭВ\n[SOAP]

' Связи бухгалтерской системы
accountant_service --> active_directory_business : Аутентификация\n[LDAP]

@enduml
