apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredVolumes
metadata:
  name: forbid-hostpath
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["audit-zone"]
  parameters:
    forbiddenHostPath: true

